eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务端地址
server:
  port: 8763 #客户端端口
spring:
  application:
    name: client #客户端名称
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.136.128
    port: 5672
env:
  dev
