spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.136.128:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.136.128
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
